### ISSUE TITLE
FEMBED UPLOAD DOCUMENTATION

### ISSUE THREAD

**Issue by dwopetweens** [marcofbb/fembed-upload-api-php#1]
Hello marcofbb . i have more than 70K rows in CSV file i would Like to import to Fembed account.can you please help on this issue

**Comment by marcofbb** [comment]
In the CSV ranks, what information do you have?

I recommend you read: https://www.fembed.com/api

**Comment by dwopetweens** [comment]
Hi,

I've csv file with over 70k++ rows which are URLs from some source, I would like to transfer them to my own account and I need some help.

Fembed Remote Transfer only allow 20 URLs to transfer at the same time, and when finished you need to manually recliam slots for next upload.

Any plugin, script could save my time would be cool.

**Comment by marcofbb** [comment]
Hi, I have not seen something programmed to do what you ask to fembed.  Although it is not very difficult to do so, we recommend that a programmer evaluate how to do it.

Add fembed support to Skype, they are always ready to help
