### ISSUE TITLE
every time want to use it don't work say "source page does not have any playable files"

### ISSUE THREAD

**Issue by jamalsaadali** [marcofbb/fembed-upload-api-php#2]
every time want to use it don't work say "source page does not have any playable files"
the links i try it
-https://dai.ly/x85fwb2
-https://www.dailymotion.com/video/x87tnpt

**Comment by marcofbb** [comment]
Hi @jamalsaadali 
What video format are you uploading?

**Comment by jamalsaadali** [comment]
i use remote transfer every time transfer video from daily motion said "this source page does not have any playable files"

**Comment by marcofbb** [comment]
Hi @jamalsaadali 
I recommend than you view this with Fembed via Ticket :/

**Comment by jamalsaadali** [comment]
don't respond

**Comment by marcofbb** [comment]
Try using a .mp4 h264 and see if the same thing happens. The video should be optimice for web ( I understand that Fembed should encode it if necessary, but sometimes it doesn't happen )

**Comment by jamalsaadali** [comment]
give me link example please

**Comment by marcofbb** [comment]
https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_480_1_5MG.mp4

**Comment by jamalsaadali** [comment]
transferd but no encode give me when play This video file cannot be played.
(Error Code: 224003)

**Comment by marcofbb** [comment]
Have you tried downloading and uploading it via web ?

**Comment by jamalsaadali** [comment]
yeah it work via web but alot of files transfer cut the time of it 
used https://www.dailymotion.com/video/x87tt4g?playlist=x5nmbq.mp4 don't transfer

**Comment by marcofbb** [comment]
I can't tell you, you are using this modified API to download the file and then upload it ? Or directly you use the remote upload of fembed ?

**Comment by jamalsaadali** [comment]
remote tranfer direct from site

**Comment by marcofbb** [comment]
There is nothing I can do. You can create a system that downloads the video to your PC and then uploads it to fembed with this script
